### ISSUE TITLE
Implement Builder, MatrixBuilder and  PositionBuilder 

### ISSUE THREAD

**Issue by NathanFiorellino** [EPFL-SV-cpp-projects/Team_8#10]
This class should handle all given inputs to compute either the PWM (or the positions)

**Comment by NathanFiorellino** [comment]
First draft committed,  began the implementation of the build() method which creates our matrix in MatrixBuilder, This reveals what will be needed from the other classes.

**Comment by yibnl** [comment]
_This is just a suggestion._

In the `MatrixBuilder` class, you have a `sum` method that computes the sum of two matrices. It may be more elegant to make this method expect an instance of `Matrix` rather than a `vector<vector<double>>`.
