### ISSUE TITLE
Clarify Interface between "Simulation" and the other classes

### ISSUE THREAD

**Issue by NathanFiorellino** [EPFL-SV-cpp-projects/Team_8#14]

**Comment by Arianedemarcillac** [comment]
- Piste d’amelioration pour la classe fast: 
Que la méthode qui lis les fichiers bed trie le tableau par ordre de chromosome pour n’ouvrir les fichier qu’une seule fois
- Deuxième façon d’executer: 
            on a toutes les méthodes de lien mais coder le output (fichier texte qui revoie la matrice) 
            créer dans la classe fasta une méthode qui renvoie un tableau avec les motifs trouvés dans le fichier bed 
- Pour la première, coder le position builder et le output
- coder une méthode qui calcule la probabilité (void proba qui rempli un vector de double
et une méthode fillPWM ) dans la classe matrix
