### ISSUE TITLE
.idea directory

### ISSUE THREAD

**Issue by alpopesc** [EPFL-SV-cpp-projects/Team_8#2]
What is a .idea directory ? It appeared after my merge. And why are there 2 .gitignore files. Can we delete one of the .gitignore files ?

**Comment by arnauddhaene** [comment]
@alpopesc The .idea folder is generated by default by your IDE (CLion, Visual Studio, etc.) and helps to compile and save information locally. As this is only relevant to you locally, it can cause errors if others pull it on their machines. Therefore, you should **never** include it in your commits and **remove it from github** as soon as possible. You can also add a command in the .gitignore such that build/ and .idea/ are never included in your commits. The only .gitignore that should remain is the one in the parent directory (thus you can delete the one in your .idea folder).
